### ISSUE TITLE
unable to build due to debian jessie expired ?

### ISSUE THREAD

**Issue by wkulesza** [scrudden/gtfs-realtime-validator-docker#5]
Excellent tool!
Unfortunatelly, when trying to build:
`docker build -t gtfs-validator .`
I'm getting this error:

W: There is no public key available for the following key IDs:
AA8E81B4331F7F50
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by scrudden** [comment]
Fixed by #6.
